#!/usr/bin/env bash
# Idempotent ComfyUI install. Safe to re-run on every boot.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

log "=== setup-comfy ==="
mkdir -p "$WORKSPACE" "$MODELS_DIR" "$VENVS_DIR" "$HF_CACHE"
apex=("git" "curl" "tmux" "rsync" "python3-venv" "ffmpeg")
apt_install "${apex[@]}"

have git || die "git is required"
have python3 || die "python3 is required"

# --- 1. ComfyUI source -------------------------------------------------------
if [[ ! -d "$COMFY_DIR/.git" ]]; then
  log "cloning ComfyUI -> $COMFY_DIR"
  git clone https://github.com/comfyanonymous/ComfyUI.git "$COMFY_DIR"
else
  log "ComfyUI already present"
fi

if [[ -n "${COMFY_REF:-}" ]]; then
  log "checking out ComfyUI ref: $COMFY_REF"
  git -C "$COMFY_DIR" fetch --all --tags --prune || true
  git -C "$COMFY_DIR" checkout "$COMFY_REF"
else
  log "updating ComfyUI (master)"
  git -C "$COMFY_DIR" pull --ff-only || warn "ComfyUI pull skipped (local changes?)"
fi

# --- 2. Python venv + deps ---------------------------------------------------
if [[ ! -x "$VENV_COMFY/bin/python" ]]; then
  log "creating ComfyUI venv -> $VENV_COMFY"
  python3 -m venv "$VENV_COMFY"
fi
install_torch_into "$VENV_COMFY"
log "installing ComfyUI requirements"
"$VENV_COMFY/bin/python" -m pip install --no-cache-dir -r "$COMFY_DIR/requirements.txt"

# --- 3. Point ComfyUI at the shared model store ------------------------------
cat > "$COMFY_DIR/extra_model_paths.yaml" <<EOF
# Generated by vast-comfy-kit. Points ComfyUI at the persistent model store.
comfyui:
    base_path: $MODELS_DIR
    checkpoints: checkpoints
    clip: clip
    clip_vision: clip_vision
    configs: configs
    controlnet: controlnet
    diffusers: diffusers
    diffusion_models: diffusion_models
    embeddings: embeddings
    loras: loras
    model_patches: model_patches
    style_models: style_models
    text_encoders: text_encoders
    unet: unet
    upscale_models: upscale_models
    vae: vae
    vae_approx: vae_approx
    sams: sams
    detection: detection
EOF
log "wrote $COMFY_DIR/extra_model_paths.yaml"

log "=== setup-comfy done ==="
